name: Actions

on:
 push:
  branches: [master]
 pull_request:
  branches: [master]
  
permissions:
  contents: write

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4
  
  - name: Configurate
    run: |
      rm -rf ${{github.workspace}}/_build
      mkdir _build && cd _build
      cmake ..
      cmake --build .

  - name: cpack
    run: |
      cd ${{github.workspace}}/_build
      cpack

  - name: package
    run: cmake --build ${{github.workspace}}/_build --target package

  - name: package_source
    run: cmake --build ${{github.workspace}}/_build --target package_source

  - name: Make a release
    uses: ncipollo/release-action@v1
    with:
      artifacts: "${{github.workspace}}/_build/*.deb,${{github.workspace}}/_build/*.tar.gz,${{github.workspace}}/_build/*.zip"
      tag: 1.0.0
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true

  - name: Arts
    uses: actions/upload-artifact@v4
    with:
        name: main
        path: ${{github.workspace}}/_build/main